name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        if: github.event.action != 'closed'
        run: |
          npm install
          npm run build

      - name: deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: packages/website/build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
